### ISSUE TITLE
Textveränderung

### ISSUE THREAD

**Issue by ToZeimetz** [sotorrent/posthistory-gt#27]
Eigentlich sieht der Post so aus:
![selection_007](https://user-images.githubusercontent.com/4719393/30278653-3fa1dd42-970b-11e7-9d05-43c79abe4f80.png)

Klick ich ein bisschen rum zwischen den Verbindungen passiert das:
![selection_006](https://user-images.githubusercontent.com/4719393/30278672-5312cd14-970b-11e7-8bed-63d84285dc06.png)

Man beachte den kleinen Unterschied rechts!

**Comment by sbaltes** [comment]
Besteht dieses Problem noch?
